### ISSUE TITLE
remove empty objects from segmentations

### ISSUE THREAD

**Issue by martinschorb** [mobie/environmental-dinoflagellate-vCLEM#1]
Hi @constantinpape ,
this is the first time I imported segmentations and it seems that there were some empty objects found in some cases.

[https://github.com/mobie/environmental-dinoflagellate-vCLEM/blob/main/photosynthetic_dinoflagellate/tables/Golgi/default.tsv](https://github.com/mobie/environmental-dinoflagellate-vCLEM/blob/main/data/photosynthetic_dinoflagellate/tables/Golgi/default.tsv)

Can I just remove the entries from the tables in these cases? Or do I need to do anything else?

**Comment by constantinpape** [comment]
Hmm, I am actually not sure how this happens. Maybe the code I am currently using to compute assumes dense ids in the segmentations. I will double check this and follow up here.

**Comment by constantinpape** [comment]
Yes, this happens when ids are not dense. Will be fixed by https://github.com/mobie/mobie-utils-python/pull/93.
In the meantime you can safely remove those rows.

**Comment by martinschorb** [comment]
Hmm, it looks like the n5 still contains references to the object labels.
After removing an empty line, I now got:
```
AnnotationAdapter: Missing annotation: Golgi; time point = 0; label = 2
Suppressing further errors of that kind.
```
and the segmentation is not shown properly.

**Comment by constantinpape** [comment]
> AnnotationAdapter: Missing annotation: Golgi; time point = 0; label = 2
> Suppressing further errors of that kind.

I am not sure where this is coming from, but the n5 shouldn't change anything in the underlying data.
Maybe @tischi knows where this is coming from in the java code.

**Comment by martinschorb** [comment]
OK, I found a solution.
Indeed the entire table row has to be removed. The IDs then no longer match, but I guess we can live with that.

**Comment by tischi** [comment]
I don't fully get what this conversation, but it looks like I don't have to do anything? 😃 ?

**Comment by constantinpape** [comment]
> The IDs then no longer match, but I guess we can live with that.

It's ok as long as the `label_id` column is there and contains the correct values (i.e. the ids for the objects we have).

**Comment by martinschorb** [comment]
Yes, I had the case where ID 1 was empty and I deleted it changing the IDs of the other segments (shifting up) and that caused the error. With the original IDs everything works.
